"""initial_migration

Revision ID: a5e8e2f618c4
Revises: 
Create Date: 2025-04-19 23:29:44.091481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users'))
    )
    op.create_index(op.f('ix__users__username'), 'users', ['username'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__chats__user_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__chats'))
    )
    op.create_index(op.f('ix__chats__user_id'), 'chats', ['user_id'], unique=False)
    op.create_table('schemas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), nullable=False),
    sa.Column('schema', sa.JSON(), nullable=True),
    sa.Column('user_message', sa.TEXT(), nullable=False),
    sa.Column('bot_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk__schemas__chat_id__chats')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__schemas'))
    )
    op.create_index(op.f('ix__schemas__chat_id'), 'schemas', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__schemas__chat_id'), table_name='schemas')
    op.drop_table('schemas')
    op.drop_index(op.f('ix__chats__user_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix__users__username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
